-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-02 09:18:23 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE books (
    book_id       INTEGER NOT NULL,
    book_name     VARCHAR2(20) NOT NULL,
    author_name   VARCHAR2(25) NOT NULL
);

ALTER TABLE books ADD CONSTRAINT books_pk PRIMARY KEY ( book_id );

CREATE TABLE patrons (
    patron_id   INTEGER NOT NULL,
    title       INTEGER
);

ALTER TABLE patrons ADD CONSTRAINT patrons_pk PRIMARY KEY ( patron_id );

CREATE TABLE transactions (
    transactions_id     INTEGER NOT NULL,
    datetime            DATE NOT NULL,
    books_book_id       INTEGER NOT NULL,
    patrons_patron_id   INTEGER NOT NULL
);

ALTER TABLE transactions
    ADD CONSTRAINT transactions_pk PRIMARY KEY ( transactions_id,
                                                 books_book_id,
                                                 patrons_patron_id );

ALTER TABLE transactions
    ADD CONSTRAINT transactions_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id );

ALTER TABLE transactions
    ADD CONSTRAINT transactions_patrons_fk FOREIGN KEY ( patrons_patron_id )
        REFERENCES patrons ( patron_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                    

            -- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-02 09:37:17 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE courses (
    course_id     INTEGER NOT NULL,
    course_name   VARCHAR2(30) NOT NULL
);

ALTER TABLE courses ADD CONSTRAINT courses_pk PRIMARY KEY ( course_id );

CREATE TABLE relation_1 (
    teachers_teacher_id   INTEGER NOT NULL,
    courses_course_id     INTEGER NOT NULL
);

ALTER TABLE relation_1 ADD CONSTRAINT relation_1_pk PRIMARY KEY ( teachers_teacher_id,
                                                                  courses_course_id );

CREATE TABLE teachers (
    teacher_id     INTEGER NOT NULL,
    teacher_name   VARCHAR2(30)
);

ALTER TABLE teachers ADD CONSTRAINT teachers_pk PRIMARY KEY ( teacher_id );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_courses_fk FOREIGN KEY ( courses_course_id )
        REFERENCES courses ( course_id );

ALTER TABLE relation_1
    ADD CONSTRAINT relation_1_teachers_fk FOREIGN KEY ( teachers_teacher_id )
        REFERENCES teachers ( teacher_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
